# Generated by Django 3.1.5 on 2021-01-28 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('Asig_cod', models.IntegerField(default='0', primary_key=True, serialize=False, verbose_name='Codigo_Asignatura')),
                ('Asig_nombre', models.CharField(max_length=50, verbose_name='Nombre_Asignatura')),
                ('Asig_niv', models.IntegerField(verbose_name='Nivel_Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('carr_codigo', models.IntegerField(default='0', primary_key=True, serialize=False, verbose_name='Codigo_Carrera')),
                ('carr_nombre', models.CharField(max_length=50, verbose_name='Nombre_Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('est_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Estado_id')),
                ('est_nom', models.CharField(max_length=20, verbose_name='Nombre_Secretariado')),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('Est_Rut', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Rut_Estudiante')),
                ('Est_Nom', models.CharField(max_length=20, verbose_name='Nombre_Estudiante')),
                ('Est_Ap', models.CharField(max_length=20, verbose_name='Apellido_Estudiante')),
                ('Est_Email', models.EmailField(max_length=254, verbose_name='Email_Estudiante')),
                ('Est_Tel', models.IntegerField(verbose_name='Telefono_Estudiante')),
                ('Est_Contrasena', models.CharField(max_length=8, verbose_name='Contraseña_Estudiante')),
                ('Est_Carr_codigo', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='operacion',
            fields=[
                ('ope_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id_Operacion')),
                ('ope_nombre', models.CharField(max_length=50, verbose_name='Nombre_Operacion')),
            ],
        ),
        migrations.CreateModel(
            name='sin_requisito',
            fields=[
                ('Sol_fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Solicitud_fecha')),
                ('Sol_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Solicitud_id')),
                ('Sol_semestre', models.CharField(max_length=500, verbose_name='Solicitud_semestre')),
                ('Sol_motivo', models.CharField(max_length=500, verbose_name='Solicitud_motivo')),
                ('Sol_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.estado')),
                ('Sol_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.estudiante')),
                ('sin_req_id_asig_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.asignatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='secretariado',
            fields=[
                ('Sec_Rut', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Rut_Secretariado')),
                ('Sec_Nom', models.CharField(max_length=20, verbose_name='Nombre_Secretariado')),
                ('Sec_Ap', models.CharField(max_length=20, verbose_name='Apellido_Secretariado')),
                ('Sec_Email', models.EmailField(max_length=254, verbose_name='Email_Secretariado')),
                ('Sec_Tel', models.IntegerField(verbose_name='Telefono_Secretariado')),
                ('Sec_Contrasena', models.CharField(max_length=20, verbose_name='Contraseña_Secretariado')),
                ('Sec_car', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='por_tope',
            fields=[
                ('Sol_fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Solicitud_fecha')),
                ('Sol_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Solicitud_id')),
                ('Sol_semestre', models.CharField(max_length=500, verbose_name='Solicitud_semestre')),
                ('Sol_motivo', models.CharField(max_length=500, verbose_name='Solicitud_motivo')),
                ('Tope_id_asig_tope', models.IntegerField(default=0, verbose_name='Id_asig_tope')),
                ('Sol_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.estado')),
                ('Sol_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.estudiante')),
                ('Tope_id_asig_ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.asignatura')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mensaje',
            fields=[
                ('men_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id_Mensaje')),
                ('men_nombre', models.CharField(max_length=50, verbose_name='Nombre_Mensaje')),
                ('men_ope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.operacion')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='Asig_car',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='SolitudeS2.carrera'),
        ),
    ]
