# Generated by Django 3.1.5 on 2021-01-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SolitudeS2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='por_tope',
            name='Tope_id_asig_ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_a_inscribir', to='SolitudeS2.asignatura'),
        ),
        migrations.AlterField(
            model_name='por_tope',
            name='Tope_id_asig_tope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tope_horario', to='SolitudeS2.asignatura'),
        ),
    ]
