# Generated by Django 3.1.5 on 2021-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolitudeS2', '0002_auto_20210128_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='est_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Estado_id'),
        ),
    ]
