# Generated by Django 3.1.5 on 2021-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolitudeS2', '0003_auto_20210128_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='est_id',
            field=models.CharField(default='0', max_length=40, primary_key=True, serialize=False, verbose_name='Estado_id'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='men_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Id_Mensaje'),
        ),
    ]
