# Generated by Django 3.1.5 on 2021-01-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolitudeS2', '0004_auto_20210128_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='por_tope',
            name='Sol_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Solicitud_id'),
        ),
        migrations.AlterField(
            model_name='sin_requisito',
            name='Sol_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Solicitud_id'),
        ),
    ]
